Adding error message when multiple files given but no time dimension specified
Otherwise, will result in a cryptic
```
assert(np.all((time[1:]-time[:-1]) > 0))
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
```
from line 300, because all in `time` array are `None`